version: 3

tasks:
  install:
    desc: Install dependencies for the agent
    cmds:
      - echo "Installing dependencies..."
      - echo "This is a placeholder for deployment commands."
    silent: true

  run:dev:
    desc: Run the agent in development mode
    cmds:
      - echo "Running agent in development mode..."
      - docker compose up --build
    silent: true

  deploy:
    desc: Deploy the agent
    cmds:
      - echo "Deploying agent..."
      - echo "This is a placeholder for deployment commands."
    silent: true